# Generated by Django 5.1.7 on 2025-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_category_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='s_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
