# Generated by Django 4.2.7 on 2024-07-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
